name: playpark
description: UI-first playground ticketing app (Flutter)
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  provider: ^6.1.2
  go_router: ^16.2.4
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^7.1.2
  intl: ^0.20.2
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.2.1
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - background.png

