name: playpark
description: UI-first playground ticketing app (Flutter)
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  provider: ^6.1.2
  go_router: ^14.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  intl: ^0.19.0
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - background.png

