services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: playpark-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: playpark
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - playpark-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: playpark-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - playpark-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: redis-server --appendonly yes

  # FastAPI Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: playpark-api
    restart: unless-stopped
    environment:
      # Application
      ENVIRONMENT: development
      DEBUG: "true"
      PORT: 50080
      
      # Security
      SECRET_KEY: "your-super-secret-key-change-in-production"
      JWT_ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 20
      REFRESH_TOKEN_EXPIRE_DAYS: 14
      
      # Database
      MONGODB_URI: "mongodb://admin:password123@mongo:27017/playpark?authSource=admin"
      MONGODB_MAX_POOL_SIZE: 50
      
      # Redis
      REDIS_URI: "redis://redis:6379/0"
      REDIS_MAX_CONNECTIONS: 20
      
      # CORS
      CORS_ORIGINS: "http://localhost:3000,http://localhost:8080,http://localhost:50080"
      
      # Rate Limiting
      RATE_LIMIT_ENABLED: "true"
      RATE_LIMIT_REQUESTS: 100
      RATE_LIMIT_WINDOW_MINUTES: 15
      
      # Logging
      LOG_LEVEL: "INFO"
      LOG_FORMAT: "json"
      
      # OAuth2
      OAUTH2_CLIENT_ID: "playpark-web"
      OAUTH2_CLIENT_SECRET: "your-oauth2-client-secret"
      OAUTH2_REDIRECT_URI: "http://localhost:3000/callback"
      
      # Monitoring
      ENABLE_METRICS: "true"
    ports:
      - "50080:50080"
    volumes:
      - ./logs:/app/logs
    networks:
      - playpark-network
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: playpark-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - playpark-network
    depends_on:
      - api
    profiles:
      - production

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  playpark-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
